plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom' version '1.16.1'
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = 'alice-offline-2612-port'
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly files('input/meteor-client.jar')
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
